### PR TITLE
Auto eslintfix

### PR DESCRIPTION
**Pull request by Akenaide**

### CODE REVIEW

**Comment by SpringsTea** [comment]
I'm going to leave this as is since I'll be renaming the repo soon.

**Comment by SpringsTea** [comment]
Sorry I chose the wrong request, I'll check this out later.

**Comment by SpringsTea** [comment]
This should also ignore anything in the /dist folder, these are the files webpack outputs and should not be modified.

How did you run the linter? When I run the lint script, there are still many many things being picked up, some im not so sure of. It also dosn't seem to like my default linebreak, probably because I develop in windows. I do like the idea of standardizing the code with a linter, but this might be difficult to get everybody on the same page. What do you think @CCondeluci?

**Comment by Akenaide** [comment]
Yeah, sure I will add this to ignore.

Well those are the changes eslint fixed alone. As you say they're are many others but they require more attention / work. I thought this 'small' changes will be enough to start the discussion.
I'll do the others in a next PR and I may need some helps.

I also kinda works on Windows and this 'issue' can be easily handle. Your editor / IDE should be able to configure your default linebreak. Maybe we can use something like https://editorconfig.org/. 
Linebreak is easy to fix, just run `eslint . --fix`. Should I add a task in package.json for this ?

**Comment by SpringsTea** [comment]
Yes, I know it will fix the linebreak, but I don't want the linter to have to comb over literally every line I write.
I think we can just disable validateLineBreaks.

**Comment by Akenaide** [comment]
I think it's better to use the default as much as possible but ok I will do that.

**Comment by SpringsTea** [comment]
So when I run eslint --fix, im still getting 71 errors. What needs to be done with those? Aren't these supposed to be resolved by the linter? Most of the errors seem to be the linter not recognizing ES2016.

**Comment by Akenaide** [comment]
I dunno, I didn't really look those. My guess is it's a mix between react syntax and obscure syntax.
I will add a react plugin hoping it will fix some.

Can we focus with the easiest first ?

**Comment by SpringsTea** [comment]
It's not obscure syntax, it's newer standards like arrow functions and spread operators. It's also identifying exported modules as unreachable code. I can't implement this without it all working correctly.

**Comment by Akenaide** [comment]
If you want only one PR for this you should said it earlier when I said I will do a other PR for those.

I'm here to help not fight with you.

I working on those.

**Comment by SpringsTea** [comment]
I'm not trying to be combative, and you don't need to make a new pull request. Once you have the linter in this branch working and configured to work with the modules that I'm currently using we can resolve this. There's no need to rush it in half finished.

**Comment by Akenaide** [comment]
My intention is not rushing it, I believe this kind of work should be done gradually. By merging it now, everyone will profit the changes and will be aware of the linter.

Waiting only increase the chances of doing work twice, because we will need to reapply on new changes.

**Comment by SpringsTea** [comment]
I would say not in this case. The linter can be configured and tested without ever actually changing the source code. I would suggest using --fix-dry-run while you work on this. That way, the only changes you're actually committing are to a few config files. Once verified that it all works, then we can merge, and **then** we can run the linter in the development branch.

**Comment by Akenaide** [comment]
I don't see your point, but we should stop talking about it.

Can you say me why react's files are .js not .jsx ?

**Comment by SpringsTea** [comment]
No reason really. There not pure jsx files so there really no reason to use one extension over another.

**Comment by Akenaide** [comment]
I think it contains not valid js code and the linter may identify react files by extension.

How do you define a pure jsx ?

**Comment by SpringsTea** [comment]
It looks like google wants js files to always be .js
https://google.github.io/styleguide/jsguide.html#file-name
airbnb wants react components to always be .jsx
From what I can tell the consensus is it dosn't really matter as long as it is consistent.

I'm fairly sure the issue is that the linter is targeting a node environment, which still does not support es6 modules by default. Check out some of the es6 configuration options in this doc: https://eslint.org/docs/user-guide/configuring

**Comment by Akenaide** [comment]
Yes Google want .js for JavaScript file. Those are not JavaScript, you return html tag in react. This is not JavaScript valid.

As you found eslint does not understand es6 but you can see in the configuration I already did the changes.

EDIT: Something felt weird when I first looked the project and this is in the google guideline you linked
`**File names must be all lowercase** and may include underscores (_) or dashes (-), but no additional punctuation. Follow the convention that your project uses. Filenames’ extension must be .js.`

**Comment by Akenaide** [comment]
So seems like es6 was not enough for React, I had to use a other parser which know about newer standard / experimental feature to maybe fix the "Unexpected Error". My bad.

Now we have mostly "no-unused-vars", "require-jsdoc", "no-tabs", "no-mixed-spaces-and-tabs".
I suppose you don't want to configure your editor to not use tabs so should I disable it ?

Unused var are simple but I may need some help for jsdoc, will you be available ?

**Comment by SpringsTea** [comment]
Having standard tabs is more reasonable, I'm willing to make that change.
Docs on the other hand I'm not interested in putting the time in for, I don't think they add much value for this application. Most of the unused vars look valid. Any time it says React is unused is because I have to include it to allow me to access {component}. I've found a fix so I don't have to do that, I'll add that to the development branch.

I don't understand though, why does the linter not fix things like mixed spaces and tabs automatically. There's no way that should have to be fixed manually.

**Comment by SpringsTea** [comment]
Looking good, getting closer.
I think we will disable react-in-jsx-scope. [This](https://stackoverflow.com/questions/42640636/react-must-be-in-scope-when-using-jsx-react-react-in-jsx-scope) discussion shows that the only alternative is to import react core and extend React.componenet, which I'm not a fan of.

no-invalid-this I don't understand at all. It wants the this scope to be the function it's contained in? Even though it needs to be the class scope.

Props type validation I'm not interested. If I wanted that I'd be using typescript.

The rest look easily resolvable.

**Comment by Akenaide** [comment]
I stop here, I don't have the motivation to apply the linter a third time.

**Pull request closed without merging**
